### ISSUE TITLE
Can't get pass the "confirm your email" screen

### ISSUE THREAD

**Issue by ashbakernz** [edrickleong/smartbank#18]
Hey downloaded this to have a play around as it looks interesting, I can get the email to send but when I select the email link it doesn't do anything, originally it just went to a http://localhost url but after I added `exp://192.168.50.127:19001` to the redirect urls I can get it to open the app back up but its still not moving me onto the next screen. I'm just learning react native and supabase at the moment so a little bit of a noob. Cheers.

I'm assuming I'm missing a simple setting somewhere

**Comment by edrickleong** [comment]
Hi @ashbakernz, thanks for checking out the repo.

Are you using the app with a real device instead of the simulator? Unfortunately, the auth redirect only works with the iOS simulator for now. I haven't figured out a way to get the auth redirect working on a real device with expo dev server.
